### ISSUE TITLE
Define language in html

### ISSUE THREAD

**Issue by Saturate** [BUSYcph/BUSYcph#1]
Hey, you forgot to define language:

https://github.com/BUSYcph/BUSYcph/blob/master/app/index.html#L2

either remove it or add a language :-)

**Comment by teltploek** [comment]
Thanks man. I'll fix this later today 👍

**Comment by teltploek** [comment]
Done. I also updated my address, so people can come visit me *wink* *wink*

Ref: 932e98c5f37a8c6dd87057a99ae88cc92e6eab59

**Comment by Saturate** [comment]
Just need opening hours then :-)

**Comment by teltploek** [comment]
Should be available [here](https://www.google.com/search?q=BUSY%20ApS%20Vesterbrogade%2090%20(baghuset)%20K%C3%B8benhavn&ludocid=8846884617714268224&hl=da) actually... but I'm mostly there mondays, tuesdays and fridays.
